# All fields under each URL are optional.

https://letterboxd.com/username/watchlist/:

https://letterboxd.com/username/list/my-list/:
  profile: HD-1080p
  root_folder: /movies
  tags: list-tag, another-tag

https://letterboxd.com/director/stanley-kubrick/:
  profile: FHD-4K

https://serializd.com/user/username/watchlist:

https://serializd.com/user/username/lists/my-list-slug:
  profile: FHD-4K
  root_folder: /tv
  tags: list-tag

https://serializd.com/list/My-Public-List-123:
  profile: Any
